### ISSUE TITLE
Typo in line 122

### ISSUE THREAD

**Issue by Directory** [SomeBotGuy/iFunny-chat-bot#1]

**Comment by SomeBotGuy** [comment]
@Gabrieldaboss65 types arent issues when it comes to variable names also that's not a typo. MIME stands for multipurpose internet mail extension. Learn more about what MIME is here https://www.tutorialspoint.com/html/mime_media_types.htm

**Comment by SomeBotGuy** [comment]
@Gabrieldaboss65 Ah yes got it. Thanks for letting me know
